server:
  port: 8091

spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:8034
        instance:
          service-base-url: http://127.0.0.1:8091
  zipkin:
    base-url: http://127.0.0.1:8041
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: cztest
    password: cztest
    virtual-host: /ego # 虚拟主机
    publisher-confirms: true # 开启消息到达交换机的确认
    publisher-returns: true #消息没有到达队列的确认
    listener:
      simple:
        concurrency: 1 # 并发数
        acknowledge-mode: manual # 签收模式-手动
  redis:
    #redis 基础配置
    # 模式：single、ms、sentinel、cluster
    model: single
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接密码（默认为空）
    password:
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 0
    url: 'redis://127.0.0.1:6379'

    #redis 连接池配置
    #池中最大链接数
    jedis:
      pool:
        # 连接池中的最大可分配实例
        max-active: 10000
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000

eureka:
  client:
    register-with-eureka: true #表示是否注册自身到eureka服务器
    fetch-registry: true #是否从eureka上获取注册信息
    registry-fetch-interval-seconds: 5 #间隔多久去拉取服务注册信息
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/ #注册节点地址

logging:
  level:
    root: info
shichang:
  test: ceshi    