server:
  port: 9506

spring:
  boot:
    admin:
      client:
        url: lb://ADMIN-SERVER
        instance:
          service-base-url: http://${spring.cloud.client.ip-address}:${server.port}
  zipkin:
    base-url: lb://ZIPKIN-SERVER
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  redis:
    database: 0
    password: 123456
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379,127.0.0.1:36379,127.0.0.1:46379    
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: cztest
    password: cztest
    virtual-host: /ego # 虚拟主机    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://CONSUMER-FEIGN
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@uriKeyResolver}' #使用SpEL按名称引用bean
                redis-rate-limiter.replenishRate: 2 #允许用户每秒处理多少个请求
                redis-rate-limiter.burstCapacity: 2000 #令牌桶的容量，允许在一秒钟内完成的最大请求数



