server:
  port: 8010

spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:8034
        instance:
          service-base-url: http://${spring.cloud.client.ip-address}:${server.port}
  zipkin:
    base-url: http://127.0.0.1:8041
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wechat_applet?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=Hongkong
    username: root
    password: root
  redis:
    #模式：single、ms、sentinel、cluster
    model: single
    #redis 基础配置
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接密码（默认为空）
    password:
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 0
    url: 'redis://127.0.0.1:6379'

    #redis 连接池配置
    #池中最大链接数
    jedis:
      pool:
        # 连接池中的最大可分配实例
        max-active: 10000
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000

eureka:
  client:
    register-with-eureka: true #表示是否注册自身到eureka服务器
    fetch-registry: true #是否从eureka上获取注册信息
    registry-fetch-interval-seconds: 5 #间隔多久去拉取服务注册信息
    serviceUrl:
      defaultZone: http://eureka1:8081/eureka/,http://eureka2:8082/eureka/,http://eureka3:8083/eureka/ #注册节点地址

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  type-aliases-package: com.beijing.user.model

thread:
  qq:
    openid: 100413274
    openkey: 0738a22b862ead14bb7976272b0a1eec
    redirect: http://www.dreamlu.net/api/qq/callback

  sina:
    openid: 4193705357
    openkey: bc7bbdfe92be06b42b38206f8bca3645
    redirect: http://www.dreamlu.net/api/sina/callback

  baidu:
    openid: xwKOgtKjbbrn9dOb7ZkGrAo5
    openkey: dNlKN4vVqgZvROrWW8twc4wESGWkSfF8
    redirect: http://www.dreamlu.net/api/baidu/callback

  renren:
    openid: 80cd6ab8bc924c97b78e06568196456e
    openkey: 51aab0e2633f43a2aeda89f299a7b4f8
    redirect: http://www.dreamlu.net/api/renren/callback

  osc:
    openid: R6XS1Qnhist6jy5UABer
    openkey: llvILNi5ThQj2YwgbM6qx7BOEKIfJjjM
    redirect: http://www.dreamlu.net/api/osc/callback

  douban:
    openid: 04e962ea4e22c5980ebc28beea6850c8
    openkey: d7ae6ac47ddf75e2
    redirect: http://www.dreamlu.net/api/douban/callback

  github:
    openid: 32413513513
    openkey: rew534563456rfh
    redirect: http://www.dreamlu.net/api/github/callback

  weixin:
    openid: wxacab1bf00bbcff11
    openkey: bd2b23927f725a6b9a1e28165c787e80
    redirect: http://www.dreamlu.net/api/weixin/callback
