server:
  port: 9507

spring:
  boot:
    admin:
      client:
        url: lb://ADMIN-SERVER
        instance:
          service-base-url: http://${spring.cloud.client.ip-address}:${server.port}
  zipkin:
    base-url: lb://ZIPKIN-SERVER
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wechat_applet?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=Hongkong
    username: root
    password: root
  redis:
    database: 0
    password: 123456
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379,127.0.0.1:36379,127.0.0.1:46379

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  type-aliases-package: com.beijing.user.model

thread:
  qq:
    openid: 100413274
    openkey: 0738a22b862ead14bb7976272b0a1eec
    redirect: http://www.dreamlu.net/api/qq/callback

  sina:
    openid: 4193705357
    openkey: bc7bbdfe92be06b42b38206f8bca3645
    redirect: http://www.dreamlu.net/api/sina/callback

  baidu:
    openid: xwKOgtKjbbrn9dOb7ZkGrAo5
    openkey: dNlKN4vVqgZvROrWW8twc4wESGWkSfF8
    redirect: http://www.dreamlu.net/api/baidu/callback

  renren:
    openid: 80cd6ab8bc924c97b78e06568196456e
    openkey: 51aab0e2633f43a2aeda89f299a7b4f8
    redirect: http://www.dreamlu.net/api/renren/callback

  osc:
    openid: R6XS1Qnhist6jy5UABer
    openkey: llvILNi5ThQj2YwgbM6qx7BOEKIfJjjM
    redirect: http://www.dreamlu.net/api/osc/callback

  douban:
    openid: 04e962ea4e22c5980ebc28beea6850c8
    openkey: d7ae6ac47ddf75e2
    redirect: http://www.dreamlu.net/api/douban/callback

  github:
    openid: 32413513513
    openkey: rew534563456rfh
    redirect: http://www.dreamlu.net/api/github/callback

  weixin:
    openid: wxacab1bf00bbcff11
    openkey: bd2b23927f725a6b9a1e28165c787e80
    redirect: http://www.dreamlu.net/api/weixin/callback
