spring:
  boot:
    admin:
      client:
        url: lb://ADMIN-SERVER
        instance:
          service-base-url: http://${spring.cloud.client.ip-address}:${server.port}
  zipkin:
    base-url: lb://ZIPKIN-SERVER
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: cztest
    password: cztest
    virtual-host: /ego # 虚拟主机
    publisher-confirms: true # 开启消息到达交换机的确认
    publisher-returns: true #消息没有到达队列的确认
    listener:
      simple:
        concurrency: 1 # 并发数
        acknowledge-mode: manual # 签收模式-手动
  redis:
    database: 0
    password: 123456
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379,127.0.0.1:36379,127.0.0.1:46379

logging:
  level:
    root: info
shichang:
  test: cececece  