eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: cloud-dev
    password: cloud-dev
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh